sudo: required
services:
  - docker
  
before_install:
  - docker build -t pjindal9/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true pjindal9/docker-react npm run test
language: generic
  